### ISSUE TITLE
Galaxy not loading games on 'Play'

### ISSUE THREAD

**Issue by OsoaGitHub** [AndrewDWhite/GalaxyGenericImporterPlugin#79]
I click play and nothing happens. I'm trying to use Cemu and Dolphin. I've set up the config file, however nothing happens.

**Comment by AndrewDWhite** [comment]
Take a look in your log files for the plugin for something like this:
2021-06-01 21:55:58,985 - root - INFO - starting
2021-06-01 21:55:58,985 - root - INFO - ""%USERPROFILE%\cemu_1.22.0\Cemu.exe" -g "Z:\data\Software\games\roms\wii u\converted.\The Legend of Zelda The Wind Waker HD\code\cking.rpx" -f"
![image](https://user-images.githubusercontent.com/972757/120412764-1d6fbb00-c325-11eb-93aa-550e016746fb.png)

This line is what the plugin is sending to the operating system to run it. If you see the line, try running that command in your command line, the part in between the quote like my example, and it should give you an error, if there was something wrong with the command that was setup.
![image](https://user-images.githubusercontent.com/972757/120412716-04ffa080-c325-11eb-9a36-f0269d0bf609.png)

Do you get an error when you try this?

**Comment by OsoaGitHub** [comment]
Both Dolphin and Cemu work perfectly in CMD, which is strange

**Comment by AndrewDWhite** [comment]
You can attach the logs to the ticket if you want, to see if I see anything.

If you look at the logs it should give you an set of internal ids for the program execution to track it. Do you see any errors here before it reports that it has finished the task?

2021-06-02 05:17:19,094 - root - INFO - starting
2021-06-02 05:17:19,094 - root - INFO - ""%USERPROFILE%\cemu_1.22.0\Cemu.exe" -g "Z:\data\Software\games\roms\wii u\converted.\Hyrule Warriors\code\ProjectZ.rpx" -f"
2021-06-02 05:17:19,095 - root - INFO - ""%USERPROFILE%\cemu_1.22.0\Cemu.exe" -g "Z:\data\Software\games\roms\wii u\converted.\Hyrule Warriors\code\ProjectZ.rpx" -f"
2021-06-02 05:17:19,095 - root - INFO - {"time": "2021-06-02T05:17:19.095812", "id": "fd8f2ab8803087b16f9a70cb2d3f034685314a02"}
2021-06-02 05:17:19,095 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 481 (launch_game)
2021-06-02 05:17:19,095 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 379 (launch_game)


Then it should report later in the logs that it stopped. Do you see this second part or is the called program hanging? You should be able to notice that the plugin will update the play time if the called application is just starting and exiting.

2021-06-02 05:17:41,801 - root - INFO - game finished
2021-06-02 05:17:41,801 - root - INFO - fd8f2ab8803087b16f9a70cb2d3f034685314a02
2021-06-02 05:17:41,802 - root - INFO - time delta calculating
2021-06-02 05:17:41,802 - root - INFO - 2021-06-02 05:17:41.802740
2021-06-02 05:17:41,802 - root - INFO - 2021-06-02 05:17:19.095812
2021-06-02 05:17:41,802 - root - INFO - 1

**Comment by OsoaGitHub** [comment]
[Here](https://pastebin.com/rSbiMYKL) is my logs, it would be great if you could take a look through it.

**Comment by AndrewDWhite** [comment]
It looks like you are missing the initial \\" in your configuration for the emulators. If you look at the example for dos you can see what I mean `  "execution" : "\"C:\\Program Files (x86)\\DOSBox-0.74-3\\DOSBox.exe\" -conf \"%ROM_RAW%\"", `

Your configuration should look more like `"execution" : "\":\\Program Files\\Cemu\\Cemu.exe\" -g \"%ROM_RAW%\" -f", ` assuming that I am reading everything else correctly.

I need to add more information about the error that you are getting from the OS, I'll create that as a ticket to follow up on.

**Comment by OsoaGitHub** [comment]
Thanks, it works perfectly now.

**Comment by AndrewDWhite** [comment]
You are welcome.

**Comment by OsoaGitHub** [comment]
The one question I have left to ask is - are game times meant to be imported from emulators?

**Comment by AndrewDWhite** [comment]
Right now they are kept internally in the cache based on the time launched from galaxy and not specifically read from the emulators. Pulling that data from those applications is something to look at in the long run. You can edit the plugin's time cache database yourself if you want to update the times, but I haven't looked into the exact process of how you would do that.

**Comment by OsoaGitHub** [comment]
Ok cool. Last thing - I have 5 games added, however the number of owned games raises by 9 after connecting the plugin, instead of 5. Is there a reason for this?

**Comment by AndrewDWhite** [comment]
Do you happen to have multiple instances of a game show up?

**Comment by AndrewDWhite** [comment]
The logs you attached show multiple installations of a few games with the same name in wii and gamecube.

**Comment by OsoaGitHub** [comment]
> 
> 
> The logs you attached show multiple installations of a few games with the same name in wii and gamecube.

That's weird. I only have one rom in my Dolphin folder: `The Legend of Zelda - Ocarina of Time.iso` which is the GameCube version that includes Master Quest.

**Comment by AndrewDWhite** [comment]
It appears that you have both the wii and gamecube entries setup to look at D:\Games\Dolphin so that would cause the duplication.

**Comment by OsoaGitHub** [comment]
> 
> 
> It appears that you have both the wii and gamecube entries setup to look at D:\Games\Dolphin so that would cause the duplication.

Ok, I have now enabled subfolder searching in Dolphin and made Wii and GameCube folders (D:\Games\Dolphin\Wii and D:\Games\Dolphin\GameCube) however there are still 9 games added, and now Ocarina of Time is an "Unknown Game" which is really odd.

**Comment by AndrewDWhite** [comment]
If you change the configuration, exit galaxy completely, delete the two cache files game_cache and game_cache-times and it will remove them from the plugin's data to send to galaxy. You will also need to disable and re-enable it again for galaxy to forget every game it got from it as well.

**Comment by OsoaGitHub** [comment]
I've done this, but there is no difference. One thing I have noticed is how all the Wii U games have multiple platforms, and if you add up all Wii U and GameCube platforms you get 9. This is probably more of a GOG Galaxy issue if having multiple platforms on the same game affects the amount of games you have.

**Comment by AndrewDWhite** [comment]
I'm not sure how it counts that. You would have to really look at what it is doing there since galaxy doesn't provide those stats back to plugins. If you look at those games you will see either something like this, where one platform is returning it multiple times, in this case it is for multiple versions of the game (pc and vita respectively).
![image](https://user-images.githubusercontent.com/972757/120877480-ba7c5f00-c584-11eb-8716-e5d8673a2700.png)
Or this where the same game is coming from multiple platforms.
![image](https://user-images.githubusercontent.com/972757/120877513-ee578480-c584-11eb-8a9b-5f6e78c0617a.png)

If it is double counting it from the first option and you are returning the same game multiple times, you can change the configuration to not return it. I don't have it automatically do this since it doesn't always make sense even for the same game since for some games they had two different disks with each having a different part of the game. (I don't remember if this was the specific example or just command and conqueror on the ps1.)
![image](https://user-images.githubusercontent.com/972757/120877578-54dca280-c585-11eb-8fd9-a82fb5b53c98.png)

Galaxy really needs more annotation features for these kinds of edge cases so you can note on each instance which is which.

**Comment by OsoaGitHub** [comment]
Ah ok. If I'm being honest I'm not too fussed, we can probably end this here. Thanks for all the support though, you've been very helpful

**Comment by AndrewDWhite** [comment]
"Unknown game"s are all an issue on galaxy's end. The short story is that every plugin suffers from this at some level because of that.

Galaxy will search their online database for the closest match; sometimes it fails and just keeps the name the plugin gave it while other times it will succeed. The plugin doesn't get any more information back. (Another integration place the plugins need feedback from galaxy to try to resolve if they can.) You are seeing a variation of https://github.com/AndrewDWhite/GalaxyGenericImporterPlugin/issues/26 . You can try to change your user id in the configuration and try your luck re-rolling all of the ids assigned to the games and seeing if it pulls the data correctly this time, since at this point you waited for their end to possibly populate something from another database. I would not be surprised if there was some local cache file somewhere that you could delete to try again, but I don't know where that would be stored and how much damage it would do to galaxy. I have the Super Mario All-Stars + Super Mario World version of that game so I don't know if they have that exact version of the game in their database.
![image](https://user-images.githubusercontent.com/972757/121653059-4bae7280-ca6a-11eb-967d-b0343740b0fb.png)

**Comment by OsoaGitHub** [comment]
BTW I figured out why extra games were being added. Essentially, in my Cemu games folder, I had my DLC and Updates folder. Turns out the plugin was scanning those games and adding them as unknowns. All I had to do was move the DLC and Updates folder to a different location and delete the cache, and then there was the correct amount of games.

**Comment by OsoaGitHub** [comment]
@AndrewDWhite sorry but I have another question, you said earlier that to change game times I can edit the cache - what app can I use to do that?

**Comment by AndrewDWhite** [comment]
I have not really played around with any apps do do that since I have been trashing my times over and over again to test different setups and will get around to it eventually. A quick search looks like this app will let you edit it and save the changes.
https://github.com/Matix-Media/PickleViewer
The ids in the time cache (game_cache-times) are the same as the ones in the other cache (game_cache).
